############
# required #
############
backend:
  name: git-gateway
  branch: develop # Branch to update (optional; defaults to master)
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads" 
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"
# required, doesn't ahve to be in use
media_library:
  name: media_lib
collections:
  - name: "static"
    label: "Static Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Hero Section, name: hero, widget: object,
             fields: [{label: Enable, name: enable, widget: boolean},
                      {label: Background Image, name: bg, widget: image},
                      {label: Title, name: title, widget: string},
                      {label: Subtitle, name: subtitle, widget: markdown},
                      {label: Button Text, name: button_text, widget: string},
                      {label: Button Url, name: button_url, widget: string}]
            }
          - label: About Section
            name: about
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Heading, name: heading, widget: markdown}
            - {label: Description, name: description, widget: markdown}
            - label: Slider Items
              name: slider_item
              widget: list
              fields:
              - {label: Image, name: image, widget: image}
          - label: Call to Action
            name: call_to_action
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Background Image, name: bg, widget: image}
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
          - label: Contact Section
            name: contact
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
          - label: Action Section
            name: action_section
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 
          - label: Find Us
            name: find_us
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
            - {label: map_base_url, name: map_base_url, widget: string}
            - {label: map_api_key, name: map_api_key, widget: string}
            - {label: map_search, name: map_search, widget: string}
            - {label: map_centre, name: map_centre, widget: string}
            - {label: map_zoom, name: map_zoom, widget: number, valueType: integer, step: 1, min: 0}
      - file: "content/test/_index.md"
        label: "Test Page"
        name: "test"
        fields:
          - label: Action Section
            name: action_section
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 
  - label: "Pages"
    name: "page"
    folder: "content/page"
    create: true 
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Content, name: body, widget: markdown}
      - {label: useFixedNav, name: useFixedNav, widget: boolean}
  - label: "Events"
    name: "events"
    folder: "content/event"
    create: true 
    delete: false 
    fields:
      - {label: Draft?, name: draft, widget: boolean, default: true}
      - {label: Creation Date, name: date, widget: datetime}
      - {label: title, name: title, widget: string}
      - {label: Description, name: description, widget: markdown}
      - {label: Image, name: image, widget: image}
      - {label: Start Date Time, name: startDate, widget: datetime}
      - {label: End Date Time, name: endDate, widget: datetime}
      - {label: Duration, name: duration, widget: string, default: "PT120M"}
      - {label: URL, name: eventUrl, widget: string, default: "https://techshedfrome.org/#find-us"}
      - {label: Publish URL, name: url, widget: string, default: "/event/<unique-name-here>" }
      - {label: Content, name: Content, widget: markdown }
      - label: Schedule
        name: eventSchedule
        widget: object
        fields: 
        - {label: startTime, name: startTime, widget: text, default: "19:00"}
        - {endTime: endTime, name: endTime, widget: text, default: "21:00"}
        - {label: Day, name: byDay, widget: text, default: "http://schema.org/Wednesday"}
        - {label: Frequency, name: repeatFrequency, widget: text, default: "P1W"}
      - label: location
        name: location
        widget: object
        fields: 
        - {label: Name, name: name, widget: text, default: "Welshmill Hub"}
        - {label: street Address, name: streetAddress, widget: text, default: "The Welsh Mill, Park Hill Drive, Frome"}
        - {label: Town, name: addressLocality, widget: text, default: "Frome"}
        - {label: Postode, name: postalCode, widget: text, default: "BA11 2LE"}
        - {label: County, name: addressRegion, widget: text, default: "Somerset"}
        - {label: Country, name: addressCountry, widget: text, default: "UK"}
  - label: "Data"
    name: "data"
    files:
      - label: "Action"
        name: "action"
        file: "data/action.yml"
        fields:
          - {label: Enable, name: enable, widget: boolean}
          - {label: section_id, name: section_id, widget: string}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - label: List
            name: list
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Icon CSS Class, name: icon, widget: string}
            - {label: Delay in Seconds, name: delay, widget: number, valueType: float, step: 0.1, min: 0}
      - label: "Navigation"
        name: "navigation"
        file: "data/navigation.yml"
        fields:
          - {label: Logo, name: logo, widget: image}
          - label: Links
            name: links
            widget: list
            fields:
            - {label: Text, name: text, widget: string}
            - {label: URL, name: url, widget: string}
      - label: "Social"
        name: "social"
        file: "data/social.yml"
        fields:
          - label: List
            name: list
            widget: list
            fields:
            - {label: Name, name: name, widget: string}
            - {label: URL, name: url, widget: markdown}
            - {label: Icon CSS Class, name: icon_classes, widget: string}
            - {label: Shown, name: shown, widget: boolean}
     

############
# optional #
############
site_url: https://techshedfrome.org/
display_url: https://techshedfrome.org/
logo_url: https://techshedfrome.org/images/tisproperjob.jpg

##