############
# required #
############
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads" 
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"
# required, doesn't ahve to be in use
media_library:
  name: media_lib
collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Services"
        name: "services"
        file: "site/data/services.yml"
        fields:
          - {label: Enable, name: enable, widget: boolean}
          - {label: section_id, name: section_id, widget: string}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: boolestringan}
          - label: List
            name: list
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Icon, name: icon, widget: string}
            - {label: Delay, name: delay, widget: string}
      - label: "Navigation"
        name: "navigation"
        file: "site/data/navigation.yml"
        fields:
          - {label: Logo, name: logo, widget: image}
          - label: Links
            name: links
            widget: list
            fields:
            - {label: Text, name: text, widget: string}
            - {label: URL, name: url, widget: string}
  
############
# optional #
############
site_url: https://mystifying-bose-12c84e.netlify.com/
display_url: mystifying-bose-12c84e.netlify.com
logo_url: https://mystifying-bose-12c84e.netlify.com/images/tisproperjob.jpg