############
# required #
############
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads" 
# The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"
# required, doesn't ahve to be in use
media_library:
  name: media_lib
collections:
  - label: "Data"
    name: "data"
    files:
      - label: "Services"
        name: "services"
        file: "data/services.yml"
        fields:
          - {label: Enable, name: enable, widget: boolean}
          - {label: section_id, name: section_id, widget: string}
          - {label: title, name: title, widget: string}
          - {label: subtitle, name: subtitle, widget: string}
          - label: List
            name: list
            widget: list
            fields:
            - {label: Title, name: title, widget: string}
            - {label: Description, name: description, widget: markdown}
            - {label: Icon CSS Class, name: icon, widget: string}
            - {label: Delay in Seconds, name: delay, widget: number, valueType: float, step: 0.1, min: 0}
      - label: "Navigation"
        name: "navigation"
        file: "data/navigation.yml"
        fields:
          - {label: Logo, name: logo, widget: image}
          - label: Links
            name: links
            widget: list
            fields:
            - {label: Text, name: text, widget: string}
            - {label: URL, name: url, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Hero Section, name: hero, widget: object,
             fields: [{label: Enable, name: enable, widget: boolean},
                      {label: Background Image, name: bg, widget: image},
                      {label: Title, name: title, widget: string},
                      {label: Subtitle, name: subtitle, widget: markdown},
                      {label: Button Text, name: button_text, widget: string},
                      {label: Button Url, name: button_url, widget: string}]
            }
          - label: About Section
            name: about
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Heading, name: heading, widget: markdown}
            - {label: Description, name: description, widget: markdown}
            - label: Slider Items
              name: slider_item
              widget: list
              fields:
              - {label: Image, name: image, widget: image}
          - label: Call to Action
            name: call_to_action
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Background Image, name: bg, widget: image}
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
          - label: Contact Section
            name: contact
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
          - label: Service Section
            name: service_section
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 
          - label: Find Us
            name: find_us
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 
            - {label: Title, name: title, widget: string}
            - {label: Subtitle, name: subtitle, widget: markdown}
            - {label: map_base_url, name: map_base_url, widget: string}
            - {label: map_api_key, name: map_api_key, widget: string}
            - {label: map_search, name: map_search, widget: string}
            - {label: map_centre, name: map_centre, widget: string}
      - file: "content/test/_index.md"
        label: "Test Page"
        name: "test"
        fields:
          - label: Service Section
            name: service_section
            widget: object
            fields: 
            - {label: Enable, name: enable, widget: boolean}
            - {label: Section Id, name: section_id, widget: string} 

############
# optional #
############
site_url: https://mystifying-bose-12c84e.netlify.com/
display_url: mystifying-bose-12c84e.netlify.com
logo_url: https://mystifying-bose-12c84e.netlify.com/images/tisproperjob.jpg